import type { Character } from './api';

// Fallback characters to use when the Jikan API rate limits us (Error 429)
export const FALLBACK_CHARACTERS: Character[] = [
    { id: 1, fullName: "Monkey D. Luffy", anime: "One Piece", image: "https://cdn.myanimelist.net/images/characters/9/310307.jpg" },
    { id: 2, fullName: "Roronoa Zoro", anime: "One Piece", image: "https://cdn.myanimelist.net/images/characters/3/100534.jpg" },
    { id: 3, fullName: "Levi Ackerman", anime: "Attack on Titan", image: "https://cdn.myanimelist.net/images/characters/2/241473.jpg" },
    { id: 4, fullName: "Killua Zoldyck", anime: "Hunter x Hunter", image: "https://cdn.myanimelist.net/images/characters/2/197241.jpg" },
    { id: 5, fullName: "Naruto Uzumaki", anime: "Naruto", image: "https://cdn.myanimelist.net/images/characters/9/131317.jpg" },
    { id: 6, fullName: "Ken Kaneki", anime: "Tokyo Ghoul", image: "https://cdn.myanimelist.net/images/characters/9/251337.jpg" },
    { id: 7, fullName: "Itachi Uchiha", anime: "Naruto", image: "https://cdn.myanimelist.net/images/characters/16/327771.jpg" },
    { id: 8, fullName: "Edward Elric", anime: "Fullmetal Alchemist", image: "https://cdn.myanimelist.net/images/characters/9/72533.jpg" },
    { id: 9, fullName: "Goku", anime: "Dragon Ball Z", image: "https://cdn.myanimelist.net/images/characters/2/241517.jpg" },
    { id: 10, fullName: "Kakashi Hatake", anime: "Naruto", image: "https://cdn.myanimelist.net/images/characters/7/284129.jpg" },
    { id: 11, fullName: "Eren Yeager", anime: "Attack on Titan", image: "https://cdn.myanimelist.net/images/characters/10/216865.jpg" },
    { id: 12, fullName: "Light Yagami", anime: "Death Note", image: "https://cdn.myanimelist.net/images/characters/6/63870.jpg" },
    { id: 13, fullName: "Saitama", anime: "One Punch Man", image: "https://cdn.myanimelist.net/images/characters/11/293463.jpg" },
    { id: 14, fullName: "Sakamata Gintoki", anime: "Gintama", image: "https://cdn.myanimelist.net/images/characters/2/242255.jpg" },
    { id: 15, fullName: "L Lawliet", anime: "Death Note", image: "https://cdn.myanimelist.net/images/characters/10/72591.jpg" },
    { id: 16, fullName: "Mikasa Ackerman", anime: "Attack on Titan", image: "https://cdn.myanimelist.net/images/characters/9/215513.jpg" },
    { id: 17, fullName: "Sosuke Aizen", anime: "Bleach", image: "https://cdn.myanimelist.net/images/characters/7/283623.jpg" },
    { id: 18, fullName: "Erza Scarlet", anime: "Fairy Tail", image: "https://cdn.myanimelist.net/images/characters/10/103624.jpg" },
    { id: 19, fullName: "Alucard", anime: "Hellsing", image: "https://cdn.myanimelist.net/images/characters/4/51351.jpg" },
    { id: 20, fullName: "Satoru Gojo", anime: "Jujutsu Kaisen", image: "https://cdn.myanimelist.net/images/characters/14/413712.jpg" },
    { id: 21, fullName: "Tanjiro Kamado", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/5/384515.jpg" },
    { id: 22, fullName: "Nezuko Kamado", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/10/384502.jpg" },
    { id: 23, fullName: "Zenitsu Agatsuma", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/10/384513.jpg" },
    { id: 24, fullName: "Inosuke Hashibira", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/12/384514.jpg" },
    { id: 25, fullName: "Kurapika", anime: "Hunter x Hunter", image: "https://cdn.myanimelist.net/images/characters/8/197240.jpg" },
    { id: 26, fullName: "Gon Freecss", anime: "Hunter x Hunter", image: "https://cdn.myanimelist.net/images/characters/11/197242.jpg" },
    { id: 27, fullName: "Sabito", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/5/384496.jpg" },
    { id: 28, fullName: "Giyu Tomioka", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/10/384517.jpg" },
    { id: 29, fullName: "Sasuke Uchiha", anime: "Naruto", image: "https://cdn.myanimelist.net/images/characters/9/131331.jpg" },
    { id: 30, fullName: "Shoto Todoroki", anime: "My Hero Academia", image: "https://cdn.myanimelist.net/images/characters/13/423069.jpg" },
    { id: 31, fullName: "Izuku Midoriya", anime: "My Hero Academia", image: "https://cdn.myanimelist.net/images/characters/10/423187.jpg" },
    { id: 32, fullName: "Katsuki Bakugo", anime: "My Hero Academia", image: "https://cdn.myanimelist.net/images/characters/13/423188.jpg" },
    { id: 33, fullName: "Megumi Fushiguro", anime: "Jujutsu Kaisen", image: "https://cdn.myanimelist.net/images/characters/8/413711.jpg" },
    { id: 34, fullName: "Nobara Kugisaki", anime: "Jujutsu Kaisen", image: "https://cdn.myanimelist.net/images/characters/4/413713.jpg" },
    { id: 35, fullName: "Yuji Itadori", anime: "Jujutsu Kaisen", image: "https://cdn.myanimelist.net/images/characters/10/423984.jpg" },
    { id: 36, fullName: "Sukuna", anime: "Jujutsu Kaisen", image: "https://cdn.myanimelist.net/images/characters/2/413726.jpg" },
    { id: 37, fullName: "Tanjirou Kamado", anime: "Demon Slayer", image: "https://cdn.myanimelist.net/images/characters/2/384515.jpg" },
    { id: 38, fullName: "Sanji", anime: "One Piece", image: "https://cdn.myanimelist.net/images/characters/5/103632.jpg" },
    { id: 39, fullName: "Nami", anime: "One Piece", image: "https://cdn.myanimelist.net/images/characters/2/263249.jpg" },
    { id: 40, fullName: "Nico Robin", anime: "One Piece", image: "https://cdn.myanimelist.net/images/characters/12/30349.jpg" },
    { id: 41, fullName: "Hisoka Morow", anime: "Hunter x Hunter", image: "https://cdn.myanimelist.net/images/characters/10/198751.jpg" },
    { id: 42, fullName: "Roy Mustang", anime: "Fullmetal Alchemist", image: "https://cdn.myanimelist.net/images/characters/10/72605.jpg" },
    { id: 43, fullName: "Kirei Kotomine", anime: "Fate/Zero", image: "https://cdn.myanimelist.net/images/characters/13/140225.jpg" },
    { id: 44, fullName: "Gilgamesh", anime: "Fate/Zero", image: "https://cdn.myanimelist.net/images/characters/4/149863.jpg" },
    { id: 45, fullName: "Saber", anime: "Fate/stay night", image: "https://cdn.myanimelist.net/images/characters/6/275200.jpg" },
    { id: 46, fullName: "Archer", anime: "Fate/stay night", image: "https://cdn.myanimelist.net/images/characters/8/166061.jpg" },
    { id: 47, fullName: "Rin Tohsaka", anime: "Fate/stay night", image: "https://cdn.myanimelist.net/images/characters/12/283259.jpg" },
    { id: 48, fullName: "Miku Nakano", anime: "The Quintessential Quintuplets", image: "https://cdn.myanimelist.net/images/characters/15/374029.jpg" },
    { id: 49, fullName: "Rem", anime: "Re:Zero", image: "https://cdn.myanimelist.net/images/characters/15/291240.jpg" },
    { id: 50, fullName: "Emilia", anime: "Re:Zero", image: "https://cdn.myanimelist.net/images/characters/15/310452.jpg" },
    { id: 51, fullName: "Subaru Natsuki", anime: "Re:Zero", image: "https://cdn.myanimelist.net/images/characters/4/314282.jpg" },
    { id: 52, fullName: "Rimuru Tempest", anime: "That Time I Got Reincarnated as a Slime", image: "https://cdn.myanimelist.net/images/characters/15/374032.jpg" }
].map(c => ({ ...c, power: 'N/A', status: 'Alive' }));
